services:
  app:
    container_name: app_container
    build:
      context : .
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports:
      - "5001:5001"
    volumes: 
      - ./:/app
    depends_on:
      database:
        condition: service_healthy
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5001", "--reload"]
    

  database:
    container_name: database_container
    image: postgres:14.19-alpine3.21
    restart: always
    env_file: 
      - .env
    ports : 
      - "5432:5432"
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  tests:
    build: ./frontend
    volumes:
      - ./:/app
    command: ["pytest", "tests/", "-v", "--color=yes", "--cov=.", "--cov-report=term-missing", "--cov-report=html"]
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env.test
  

  frontend:
    container_name: frontend_container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"     # ‚Üê Le bon port !
    depends_on:
      - app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]


      
volumes:
  postgres_data_auth:
    


